### ISSUE TITLE
Users can delete Quests without being Member of BOT_ADMINS

### ISSUE THREAD

**Issue by GCHarald** [florianbecker/PokemonQuestBot#25]
In the config.php I set BOT_ADMINS only to concrete persons. BOT_ACCESS is empty.
So everyone should have access to the bot. 
But as shown in the Access Overview, only BOT_ADMINS should be able to delete Quests.
Some User reported to me, that they can delete Quest via /list -> Select a Pokestop -> Select "Delete". This shouldn't be possible.

**Comment by Chefkeks** [comment]
True... Oops ^^
Looks like we forgot to implement the check for permissions in the process. As I plan to revamp permissions and have other changes in mind (as mentioned in the Telegram Dev and Support group), I will include the fix with the upcoming other changes.
Anyway, Thanks for the report :)
